# Generated by Django 4.2.6 on 2024-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodon', '0002_contactdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
