# Generated by Django 4.2.6 on 2024-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodon', '0003_alter_contactdata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
